name: Create New Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  ci:
    name: Create New release
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: python3 -m pip install setuptools

      - name: Package Code
        run: python3 setup.py sdist bdist_wheel

      - name: Check if release tag exists
        uses: bbonkr/git-tag-check-action@v1
        id: release_tag
        with:
          tag: 'v${{ steps.pypass_version.outputs.value }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag for new Release
        if: steps.release_tag.outputs.tag == ''
        uses: makethenetgo/actions-create-tag@v1
        with:
          tag_name: "v${{ steps.pypass_version.outputs.value }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.pypass_version.outputs.value }}"
          draft: true
          bodyFile: "./CHANGELOG.md"
          artifacts: "dist/*"
